// 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

// Approach-->1(Using Hash)
class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        unordered_map<char, int> mp;

        for (char x : s)
        {
            mp[x]++;
        }

        char ans;

        for (char ch : t)
        {
            if (mp[ch] == 0)
            {
                ans = ch;
            }
            mp[ch]--;
        }

        return ans;
    }
};
// TC-->O(N)
// SC-->(s.len)

// Approach-->2(Using ASCII values)
class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        int sum = 0;

        for (char &ch : t)
        {
            sum += ch;
        }

        for (char &ch : s)
        {
            sum -= ch;
        }

        return (char)sum;
    }
};
// TC-->O(N)
// SC-->O(1)

// Approach-->3(Using XOR)
class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        int XOR = 0;

        for (char &ch : s)
        {
            XOR ^= ch;
        }

        for (char &ch : t)
        {
            XOR ^= ch;
        }

        return (char)XOR;
    }
};
// TC-->O(N)
// SC-->O(1)